version: '3.1'
services:
  minio:
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_REGION_NAME=default
      - MINIO_IDENTITY_OPENID_CLAIM_NAME=tag
      - MINIO_IDENTITY_OPENID_REDIRECT_URI=http://localhost:9001/oauth_callback
    command: ["minio", "server", "/data/{0...3}", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - '9001:9001'
    volumes:
      - oss-data:/data

  oss:
    restart: always
    image: casbin/casdoor:v1.110.0
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./app.conf:/conf/app.conf
  db:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_DB: casdoor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  oss-data:
